-- Stories: ephemeral photo status, expires 24h after posting.

create table if not exists public.stories (
  id          bigint generated by default as identity primary key,
  username    text not null,
  image_url   text not null,
  caption     text check (caption is null or char_length(caption) <= 200),
  created_at  timestamptz not null default now(),
  expires_at  timestamptz not null default now() + interval '24 hours'
);

create index if not exists stories_active_idx on public.stories (expires_at desc);
create index if not exists stories_username_idx on public.stories (username, created_at desc);

alter table public.stories enable row level security;

drop policy if exists "stories_select_active" on public.stories;
create policy "stories_select_active" on public.stories
  for select to authenticated
  using (expires_at > now() or username = public.my_username());

drop policy if exists "stories_insert_own" on public.stories;
create policy "stories_insert_own" on public.stories
  for insert to authenticated
  with check (username = public.my_username());

drop policy if exists "stories_delete_own" on public.stories;
create policy "stories_delete_own" on public.stories
  for delete to authenticated
  using (username = public.my_username());

-- Same per-account rate-limit scheme as migration 016
drop trigger if exists trg_rl_stories on public.stories;
create trigger trg_rl_stories before insert on public.stories
  for each row execute function public.enforce_rate_limit('username', '10', '3600');

-- Storage bucket for story photos
insert into storage.buckets (id, name, public, allowed_mime_types, file_size_limit)
values ('stories', 'stories', true, '{"image/jpeg"}', 5242880)
on conflict (id) do update
  set public             = excluded.public,
      allowed_mime_types = excluded.allowed_mime_types,
      file_size_limit    = excluded.file_size_limit;

-- Extend the media object policies (created in 017) to cover the stories bucket
drop policy if exists "media_insert_own_folder" on storage.objects;
create policy "media_insert_own_folder" on storage.objects
  for insert to authenticated
  with check (
    bucket_id in ('event-covers', 'chat-media', 'stories')
    and (storage.foldername(name))[1] = auth.uid()::text
  );

drop policy if exists "media_update_own_folder" on storage.objects;
create policy "media_update_own_folder" on storage.objects
  for update to authenticated
  using (
    bucket_id in ('event-covers', 'chat-media', 'stories')
    and (storage.foldername(name))[1] = auth.uid()::text
  )
  with check (
    bucket_id in ('event-covers', 'chat-media', 'stories')
    and (storage.foldername(name))[1] = auth.uid()::text
  );

drop policy if exists "media_delete_own_folder" on storage.objects;
create policy "media_delete_own_folder" on storage.objects
  for delete to authenticated
  using (
    bucket_id in ('event-covers', 'chat-media', 'stories')
    and (storage.foldername(name))[1] = auth.uid()::text
  );

drop policy if exists "media_read" on storage.objects;
create policy "media_read" on storage.objects
  for select to authenticated
  using (bucket_id in ('event-covers', 'chat-media', 'stories'));
