-- Pages: owner/moderator posts, moderator roles, and follower-growth tracking.

-- Follower growth needs a timestamp; existing rows get a "now" baseline.
alter table public.page_followers add column if not exists created_at timestamptz not null default now();

create table if not exists public.page_posts (
  id         bigint generated by default as identity primary key,
  page_id    bigint not null references public.pages(id) on delete cascade,
  username   text not null,
  content    text not null check (char_length(content) between 1 and 2000),
  created_at timestamptz not null default now()
);

create table if not exists public.page_moderators (
  id         bigint generated by default as identity primary key,
  page_id    bigint not null references public.pages(id) on delete cascade,
  username   text not null,
  added_by   text not null,
  created_at timestamptz not null default now(),
  unique (page_id, username)
);

create index if not exists page_posts_page_idx on public.page_posts (page_id, created_at desc);
create index if not exists page_moderators_page_idx on public.page_moderators (page_id);

-- True when the current user owns the page or moderates it.
create or replace function public.can_manage_page(pid bigint)
returns boolean
language sql
stable
set search_path = public
as $$
  select exists (
    select 1 from public.pages
    where id = pid and created_by = public.my_username()
  ) or exists (
    select 1 from public.page_moderators
    where page_id = pid and username = public.my_username()
  );
$$;

alter table public.page_posts enable row level security;

drop policy if exists "page_posts_select" on public.page_posts;
create policy "page_posts_select" on public.page_posts
  for select using (auth.uid() is not null);

drop policy if exists "page_posts_insert" on public.page_posts;
create policy "page_posts_insert" on public.page_posts
  for insert with check (username = public.my_username() and public.can_manage_page(page_id));

drop policy if exists "page_posts_delete" on public.page_posts;
create policy "page_posts_delete" on public.page_posts
  for delete using (username = public.my_username() or public.can_manage_page(page_id));

alter table public.page_moderators enable row level security;

drop policy if exists "page_moderators_select" on public.page_moderators;
create policy "page_moderators_select" on public.page_moderators
  for select using (auth.uid() is not null);

-- Only the page OWNER manages moderators (moderators cannot add moderators)
drop policy if exists "page_moderators_insert" on public.page_moderators;
create policy "page_moderators_insert" on public.page_moderators
  for insert with check (
    added_by = public.my_username()
    and exists (select 1 from public.pages where id = page_id and created_by = public.my_username())
  );

drop policy if exists "page_moderators_delete" on public.page_moderators;
create policy "page_moderators_delete" on public.page_moderators
  for delete using (
    exists (select 1 from public.pages where id = page_id and created_by = public.my_username())
  );

-- Same per-account rate-limit scheme as migration 016
drop trigger if exists trg_rl_page_posts on public.page_posts;
create trigger trg_rl_page_posts before insert on public.page_posts
  for each row execute function public.enforce_rate_limit('username', '20', '3600');
